batch_size: 1
beam_size: 10
penalty: 0.0
maxlenratio: 0.0
minlenratio: 0.0
lm_weight: 0.0
ctc_weight: 0.0
hyp_primer: ["<startoftranscript>", "<translateja>", "<notimestamps>"]
log_level: INFO   # DEBUG
